### ISSUE TITLE
Sequence in the process of predict?

### ISSUE THREAD

**Issue by manhcntt21** [Isminoula/TextNormSeq2Seq#3]
I have a stupid question, hope you explain it to me.

I have not understood how the two model words and characters combine in the predictive process to normalize sentences

**Comment by Isminoula** [comment]
No question is stupid, I am here to help! 

If you mean how we combine the word and character models, the idea is that when a word is out-of-vocabulary (OOV) then it is typically represented as 'unknown' (UNK). All OOV words are essentially mapped to this symbol. We start with a [word level model](https://github.com/Isminoula/TextNormSeq2Seq/blob/882da6be33a2d95fa38546274d719a482e71298d/lib/train/evaluator.py#L32) that predicts a target word for each source word. If a word in the source language (here, informal tweets) is not in the model vocabulary (UNK), we can simply copy the word from the source sentence. Or better yet, we use the [character level model](https://github.com/Isminoula/TextNormSeq2Seq/blob/882da6be33a2d95fa38546274d719a482e71298d/lib/train/evaluator.py#L48) to predict the target word (translate to format language)

If your question was about something else, e.g. specific to the details of _handle_unk_ function, please comment with more details and I will get back to you ASAP. :)

**Comment by manhcntt21** [comment]
I'm sorry, I can answer you now. Actually, I still have a lot of places to clarify, but my English is not good, so I have to use gg translate, sorry for that.

As far as I read the code and paper, the use of the previous word_model or the previous character is nothing else.

Because the character model is only used to standardize (unk work) whereas word doesn't have any effect on this.

In addition, I have a bit of understanding in line 58 of file trainer.py. Why add up?

**Comment by Isminoula** [comment]
So sorry for the late reply, I was moving for a new job... Hope it is not too late!

Do you mean that when dealing with UNK we do not take into account any information from the previous word, as done through the LSTM? If yes, that is correct and actually I do not know any way to use this information as we switch to a completely different model.
If the comment was on something else, please explain further.

For line 58, this is just to print out how many words are being processed in total (source and target) per second (words_pers). You could also track each individually, e.g.
` words_pers_src  = int(src.data.ne(lib.constants.PAD).sum().item() / (time.time() - epoch_time))
words_pers_tgt  = int(tgt.data.ne(lib.constants.PAD).sum().item() / (time.time() - epoch_time))`

**Comment by manhcntt21** [comment]
No problem.

I am having difficulty changing a bit of model, I want to implement character model with UNK words, then do word model with sentences when there are no more UNK words, can you support me?

As soon as possible, I look forward to it, if it is answered today.

Thank you

**Comment by manhcntt21** [comment]
As for the previous question, I see that in line 58 here, I have done the addition of tgt and src, in my opinion, just src or tgt, not both.

[<a href="https://ibb.co/d53Rm57"><img src="https://i.ibb.co/6WpkXWN/Screenshot-from-2019-12-24-21-31-29.png" alt="Screenshot-from-2019-12-24-21-31-29" border="0"></a>](url)

**Comment by Isminoula** [comment]
Hi @manhcntt21 

In word models, UNK makes sense because common Seq2Seq cannot handle very large vocabularies, so typically the UNK is used to shrink the vocabulary down to manageable sizes. Character models usually do not have UNK words, as they can handle any type of word without expanding the vocabulary to a very large size (at least for most languages - as far as I know).
Nevertheless, if you still want to have UNK then you need to limit the character vocabulary and have a special token (1 character only) for unknown characters. 

Also, on longer sequences (for example full sentences) the character model takes much longer to train than word models. This reason (and semantics) is why word models are more common instead of character models. 

If what you are trying to do is to have a character model on full sentences then the word model afterwards is not needed. 

If you want to use character model on word pairs (as it is now) and then go to sentence level, then a quick solution would be to 1) train the character model (spelling_model) and 2) use to to predict each word per sentence and save the predictions for each sentence into a new json file with the same format as the train data and 3) take this new file and use it to train a word-level model (S2S). If you need help with specific commands, let me know!

**Comment by manhcntt21** [comment]
thank you!

for me about a while longer, will continue to discuss the issue.

Now, I want to ask why, I changed the max_train_decode_len, according to the input and target max of my dataset, but got the error:index 68 is out of bounds for dimension 0 with size 68

**Comment by manhcntt21** [comment]
oh. Thank you, since I am used to not adding padding e and s  = 70, I have an error.

I'm a little busy right now, I'll continue the story soon, sorry

**Comment by Isminoula** [comment]
Glad you figured it out, let me know if you need anything! Happy New Year!

**Comment by manhcntt21** [comment]
I don't understand why, my data was formatted according to your format, but this error occurred during training:

I need to run with python3 because it can handle vietnamese. 

and this example: my data 
https://github.com/manhcntt21/TextNormSeq2Seq/blob/master/dataset/data/train_tiny.json
https://github.com/manhcntt21/TextNormSeq2Seq/blob/master/dataset/data/test_tiny.json

File "main.py", line 102, in <module>
    main()
  File "main.py", line 95, in main
    test_evaluator.eval(test_data, pred_file=pred_file)
  File "/home/manh/Documents/TextNormSeq2Seq/lib/train/evaluator.py", line 31, in eval
    outputs = self.model(batch, eval=True)
  File "/home/manh/anaconda3/envs/work-ra3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/manh/Documents/TextNormSeq2Seq/lib/model/model.py", line 118, in forward
    decoder_output, decoder_hidden, attention_weights = self.decoder(input_seq, src_lens, encoder_outputs, decoder_hidden)
  File "/home/manh/anaconda3/envs/work-ra3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/manh/Documents/TextNormSeq2Seq/lib/model/model.py", line 70, in forward
    decoder_output, self.decoder_hidden = self.rnn(emb, decoder_hidden)
  File "/home/manh/anaconda3/envs/work-ra3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/manh/anaconda3/envs/work-ra3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 559, in forward
    return self.forward_tensor(input, hx)
  File "/home/manh/anaconda3/envs/work-ra3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 539, in forward_tensor
    output, hidden = self.forward_impl(input, hx, batch_sizes, max_batch_size, sorted_indices)
  File "/home/manh/anaconda3/envs/work-ra3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 519, in forward_impl
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/manh/anaconda3/envs/work-ra3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 490, in check_forward_args
    self.check_input(input, batch_sizes)
  File "/home/manh/anaconda3/envs/work-ra3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 149, in check_input
    expected_input_dim, input.dim()))
RuntimeError: input must have 3 dimensions, got 2`
`

**Comment by manhcntt21** [comment]
Happy New Year!

**Comment by manhcntt21** [comment]
you let me ask, what does score in test.pred and valid.pred file mean. Thank you.

**Comment by manhcntt21** [comment]
I want to confirm that accuracy during trainning is calculated by number corret / number targer (the length of the target sentence includes all the characters without leaving any).

and precision and recall, only on nonstandart characters.

is it right?

**Comment by Isminoula** [comment]
Hi @manhcntt21, 

score in the test.pred and valid.pred files is the F1 for this instance ([sent_f1](https://github.com/Isminoula/TextNormSeq2Seq/blob/1ba38ac7a9b930ae1b8db0e9293db31ec84002f9/lib/train/evaluator.py#L53))

You got these below correct!
- accuracy is exactly what you mentioned, there is a max_len [here](https://github.com/Isminoula/TextNormSeq2Seq/blob/882da6be33a2d95fa38546274d719a482e71298d/lib/train/trainer.py#L56) for the padding mask but goes up to the target length
- precision, recall and f1 only on non-standard characters, but also penalizing tokens that have changed when they should have remained the same (unnecessary normalizations)

**Comment by Isminoula** [comment]
Closing old issue
