### ISSUE TITLE
download link fo pretrained models not working

### ISSUE THREAD

**Issue by amonsoes** [Isminoula/TextNormSeq2Seq#5]
Hello,

As the title already indicates, the download link for the pretrained models needs an update.

Other question:

Are the hyperparams used for training the two models, which are suggested in the README, the ones you used to obtain the results stated in the paper?

best wishes,
Amon

**Comment by Isminoula** [comment]
Hello Amon,

I just corrected the link, please let me know if it works. As far as the hyper-parameters go (and as far as I remember) the README contains the ones used to obtain the results in the paper (also listed in Table 2).

Best,
Ismini

**Comment by amonsoes** [comment]
Works like a charm! Thank you very much for your swift reply.
